version: 2

models:
  - name: mdw_stg_categories
    description: "Staging view for product categories. Cleans and type-casts raw category data."
    columns:
      - name: category_id
        description: "Primary key. Unique identifier for each product category."
        tests:
          - unique
          - not_null
      - name: category_name
        description: "Name of the product category."
        tests:
          - not_null

  - name: mdw_stg_countries
    description: "Staging view for countries. Cleans and type-casts raw country data."
    columns:
      - name: country_id
        description: "Primary key. Unique identifier for each country."
        tests:
          - unique
          - not_null
      - name: country_name
        description: "Name of the country."
        tests:
          - not_null
      - name: country_code
        description: "ISO 3166-1 alpha-2 country code."
        tests:
          - not_null

  - name: mdw_stg_cities
    description: "Staging view for cities. Cleans and type-casts raw city data."
    columns:
      - name: city_id
        description: "Primary key. Unique identifier for each city."
        tests:
          - unique
          - not_null
      - name: city_name
        description: "Name of the city."
        tests:
          - not_null
      - name: zipcode
        description: "Zipcode of the city."
        tests:
          - not_null
      - name: country_id
        description: "Foreign key to mdw_stg_countries."
        tests:
          - not_null

  - name: mdw_stg_customers
    description: "Staging view for customers. Cleans and type-casts raw customer data."
    columns:
      - name: customer_id
        description: "Primary key. Unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the customer."
        tests:
          - not_null
      - name: middle_initial
        description: "Middle initial of the customer."
      - name: last_name
        description: "Last name of the customer."
        tests:
          - not_null
      - name: city_id
        description: "Foreign key to mdw_stg_cities."
        tests:
          - not_null
      - name: address
        description: "Residential address of the customer."
        tests:
          - not_null

  - name: mdw_stg_employees
    description: "Staging view for employees/salespersons. Cleans and type-casts raw employee data."
    columns:
      - name: employee_id
        description: "Primary key. Unique identifier for each employee."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the employee."
        tests:
          - not_null
      - name: middle_initial
        description: "Middle initial of the employee."
      - name: last_name
        description: "Last name of the employee."
        tests:
          - not_null
      - name: birth_date
        description: "Date of birth of the employee."
        tests:
          - not_null
      - name: gender
        description: "Gender of the employee."
        tests:
          - not_null
      - name: city_id
        description: "Foreign key to mdw_stg_cities."
        tests:
          - not_null
      - name: hire_date
        description: "Date when the employee was hired."
        tests:
          - not_null

  - name: mdw_stg_products
    description: "Staging view for products. Cleans and type-casts raw product data."
    columns:
      - name: product_id
        description: "Primary key. Unique identifier for each product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
      - name: price
        description: "Price per unit of the product."
        tests:
          - not_null
      - name: category_id
        description: "Foreign key to mdw_stg_categories."
        tests:
          - not_null
      - name: class
        description: "Classification of the product."
      - name: modify_date
        description: "Last modified date."
      - name: resistant
        description: "Product resistance category."
      - name: is_allergic
        description: "Indicates whether the item is an allergen."
      - name: vitality_days
        description: "Product vitality/shelf-life in days."

  - name: mdw_stg_sales
    description: "Staging view for sales transactions. Cleans and type-casts raw sales data."
    columns:
      - name: sales_id
        description: "Primary key. Unique identifier for each sale."
        tests:
          - unique
          - not_null
      - name: salesperson_id
        description: "Foreign key to mdw_stg_employees."
        tests:
          - not_null
      - name: customer_id
        description: "Foreign key to mdw_stg_customers."
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to mdw_stg_products."
        tests:
          - not_null
      - name: quantity
        description: "Number of units sold."
        tests:
          - not_null
      - name: discount
        description: "Discount applied to the sale."
      - name: total_price
        description: "Final sale price after discounts."
        tests:
          - not_null
      - name: sales_at
        description: "Timestamp of the sale."
        tests:
          - not_null
      - name: transaction_number
        description: "Unique identifier for the transaction."
        tests:
          - not_null
