version: 2

models:
  - name: mdw_cur_daily_sales
    description: "Daily aggregated sales metrics for overall business trend analysis. One row per day. Incremental with merge strategy using date_key as unique key."
    columns:
      - name: date_key
        description: "Primary key. Native DATE type. The date of the aggregated sales data."
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component of the date."
        tests:
          - not_null
      - name: quarter
        description: "Quarter of the year (1-4)."
        tests:
          - not_null
      - name: month
        description: "Month component of the date (1-12)."
        tests:
          - not_null
      - name: year_month
        description: "Year and month in YYYY-MM format."
        tests:
          - not_null
      - name: month_name
        description: "Full name of the month."
        tests:
          - not_null
      - name: day_name
        description: "Full name of the day."
        tests:
          - not_null
      - name: day_type
        description: "Day type classification: Weekend or Weekday."
        tests:
          - not_null
      - name: total_transactions
        description: "Count of unique sales transactions on this date."
        tests:
          - not_null
      - name: unique_customers
        description: "Count of distinct customers who made purchases."
        tests:
          - not_null
      - name: unique_products
        description: "Count of distinct products sold."
        tests:
          - not_null
      - name: active_salespersons
        description: "Count of distinct salespersons who made sales."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total units sold across all transactions."
        tests:
          - not_null
      - name: gross_revenue
        description: "Total gross revenue before discounts."
        tests:
          - not_null
      - name: total_discounts
        description: "Total discounts given across all transactions."
        tests:
          - not_null
      - name: net_revenue
        description: "Total net revenue after discounts."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average value per transaction."
      - name: avg_quantity_per_transaction
        description: "Average quantity sold per transaction."
      - name: avg_discount_rate
        description: "Average discount rate applied per transaction."
      - name: partition
        description: "Partition key in YYYYMMDD format."
        tests:
          - not_null

  - name: mdw_cur_product_performance
    description: "Daily product-level performance metrics for product analysis and ranking. Incremental with merge strategy using [date_key, product_sk] as unique key."
    columns:
      - name: date_key
        description: "The date of the aggregated product data. Native DATE type."
        tests:
          - not_null
      - name: year
        description: "Year component of the date."
        tests:
          - not_null
      - name: quarter
        description: "Quarter of the year (1-4)."
        tests:
          - not_null
      - name: month
        description: "Month component of the date (1-12)."
        tests:
          - not_null
      - name: year_month
        description: "Year and month in YYYY-MM format."
        tests:
          - not_null
      - name: month_name
        description: "Full name of the month."
        tests:
          - not_null
      - name: day_name
        description: "Full name of the day."
        tests:
          - not_null
      - name: day_type
        description: "Day type classification: Weekend or Weekday."
        tests:
          - not_null
      - name: product_sk
        description: "Surrogate key to product dimension."
        tests:
          - not_null
      - name: product_id
        description: "Natural key. Unique identifier for each product."
        tests:
          - not_null
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
      - name: category_id
        description: "Foreign key to product category."
      - name: category_name
        description: "Name of the product category."
      - name: product_class
        description: "Classification of the product."
      - name: allergic_type
        description: "Allergic type classification."
      - name: total_transactions
        description: "Count of transactions for this product on this date."
        tests:
          - not_null
      - name: unique_customers
        description: "Count of distinct customers who bought this product."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total units of this product sold."
        tests:
          - not_null
      - name: gross_revenue
        description: "Gross revenue from this product."
        tests:
          - not_null
      - name: total_discounts
        description: "Total discounts applied to this product."
        tests:
          - not_null
      - name: net_revenue
        description: "Net revenue from this product."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average transaction value for this product."
      - name: avg_quantity_per_transaction
        description: "Average quantity per transaction for this product."
      - name: min_unit_price
        description: "Minimum unit price observed for this product."
      - name: max_unit_price
        description: "Maximum unit price observed for this product."
      - name: partition
        description: "Partition key in YYYYMMDD format."
        tests:
          - not_null

  - name: mdw_cur_customer_summary
    description: "Customer-level summary metrics for segmentation and lifetime value analysis. One row per customer. Incremental with merge strategy using customer_sk as unique key. Uses ARRAY types for accurate distinct count tracking across incremental runs."
    columns:
      - name: customer_sk
        description: "Primary key. Surrogate key to customer dimension."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural key. Unique identifier for each customer."
        tests:
          - not_null
      - name: customer_name
        description: "Full name of the customer."
        tests:
          - not_null
      - name: customer_city
        description: "City where the customer resides."
      - name: customer_country
        description: "Country where the customer resides."
      - name: customer_country_code
        description: "ISO country code of the customer."
      - name: first_purchase_date
        description: "Date of the customer's first purchase."
        tests:
          - not_null
      - name: last_purchase_date
        description: "Date of the customer's most recent purchase."
        tests:
          - not_null
      - name: customer_tenure_days
        description: "Number of days between first and last purchase."
      - name: total_transactions
        description: "Total number of transactions by this customer."
        tests:
          - not_null
      - name: active_days
        description: "Number of distinct days the customer made purchases."
        tests:
          - not_null
      - name: purchased_product_sks
        description: "Array of product surrogate keys purchased by this customer for accurate distinct tracking."
        tests:
          - not_null
      - name: purchased_category_ids
        description: "Array of category IDs purchased by this customer for accurate distinct tracking."
        tests:
          - not_null
      - name: unique_products_purchased
        description: "Count of distinct products purchased (cardinality of purchased_product_sks)."
        tests:
          - not_null
      - name: unique_categories_purchased
        description: "Count of distinct categories purchased from (cardinality of purchased_category_ids)."
        tests:
          - not_null
      - name: total_quantity_purchased
        description: "Total units purchased by this customer."
        tests:
          - not_null
      - name: lifetime_gross_revenue
        description: "Total gross revenue from this customer."
        tests:
          - not_null
      - name: lifetime_discounts
        description: "Total discounts given to this customer."
        tests:
          - not_null
      - name: lifetime_net_revenue
        description: "Total net revenue from this customer."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average transaction value for this customer."
      - name: avg_quantity_per_transaction
        description: "Average quantity per transaction for this customer."
      - name: avg_transactions_per_active_day
        description: "Average transactions per day when customer was active."

  - name: mdw_cur_salesperson_performance
    description: "Daily salesperson performance metrics for sales team analysis and performance tracking. Incremental with merge strategy using [date_key, salesperson_sk] as unique key."
    columns:
      - name: date_key
        description: "The date of the aggregated salesperson data. Native DATE type."
        tests:
          - not_null
      - name: year
        description: "Year component of the date."
        tests:
          - not_null
      - name: quarter
        description: "Quarter of the year (1-4)."
        tests:
          - not_null
      - name: month
        description: "Month component of the date (1-12)."
        tests:
          - not_null
      - name: year_month
        description: "Year and month in YYYY-MM format."
        tests:
          - not_null
      - name: month_name
        description: "Full name of the month."
        tests:
          - not_null
      - name: day_name
        description: "Full name of the day."
        tests:
          - not_null
      - name: day_type
        description: "Day type classification: Weekend or Weekday."
        tests:
          - not_null
      - name: salesperson_sk
        description: "Surrogate key to employee dimension."
        tests:
          - not_null
      - name: salesperson_id
        description: "Natural key. Unique identifier for each salesperson."
        tests:
          - not_null
      - name: salesperson_name
        description: "Full name of the salesperson."
        tests:
          - not_null
      - name: salesperson_city
        description: "City where the salesperson is located."
      - name: salesperson_country
        description: "Country where the salesperson is located."
      - name: salesperson_country_code
        description: "ISO country code of the salesperson."
      - name: total_transactions
        description: "Count of transactions handled by this salesperson."
        tests:
          - not_null
      - name: unique_customers_served
        description: "Count of distinct customers served."
        tests:
          - not_null
      - name: unique_products_sold
        description: "Count of distinct products sold."
        tests:
          - not_null
      - name: unique_categories_sold
        description: "Count of distinct categories sold."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total units sold by this salesperson."
        tests:
          - not_null
      - name: gross_revenue
        description: "Gross revenue generated by this salesperson."
        tests:
          - not_null
      - name: total_discounts_given
        description: "Total discounts given by this salesperson."
        tests:
          - not_null
      - name: net_revenue
        description: "Net revenue generated by this salesperson."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average transaction value for this salesperson."
      - name: avg_quantity_per_transaction
        description: "Average quantity per transaction for this salesperson."
      - name: avg_discount_rate
        description: "Average discount rate for this salesperson."
      - name: partition
        description: "Partition key in YYYYMMDD format."
        tests:
          - not_null

  - name: mdw_cur_category_daily_sales
    description: "Daily category-level sales metrics for category management and trend analysis. Incremental with merge strategy using [date_key, category_id] as unique key."
    columns:
      - name: date_key
        description: "The date of the aggregated category data. Native DATE type."
        tests:
          - not_null
      - name: year
        description: "Year component of the date."
        tests:
          - not_null
      - name: quarter
        description: "Quarter of the year (1-4)."
        tests:
          - not_null
      - name: month
        description: "Month component of the date (1-12)."
        tests:
          - not_null
      - name: year_month
        description: "Year and month in YYYY-MM format."
        tests:
          - not_null
      - name: month_name
        description: "Full name of the month."
        tests:
          - not_null
      - name: day_name
        description: "Full name of the day."
        tests:
          - not_null
      - name: day_type
        description: "Day type classification: Weekend or Weekday."
        tests:
          - not_null
      - name: category_id
        description: "Foreign key to product category."
        tests:
          - not_null
      - name: category_name
        description: "Name of the product category."
        tests:
          - not_null
      - name: total_transactions
        description: "Count of transactions in this category."
        tests:
          - not_null
      - name: unique_customers
        description: "Count of distinct customers who bought from this category."
        tests:
          - not_null
      - name: unique_products_sold
        description: "Count of distinct products sold in this category."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total units sold in this category."
        tests:
          - not_null
      - name: gross_revenue
        description: "Gross revenue from this category."
        tests:
          - not_null
      - name: total_discounts
        description: "Total discounts applied in this category."
        tests:
          - not_null
      - name: net_revenue
        description: "Net revenue from this category."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average transaction value in this category."
      - name: avg_quantity_per_transaction
        description: "Average quantity per transaction in this category."
      - name: partition
        description: "Partition key in YYYYMMDD format."
        tests:
          - not_null
