version: 2

sources:
  - name: grocery
    description: "Grocery sales raw data stored in S3 as CSV files"
    database: awsdatacatalog
    schema: mdw_raw
    tables:
      - name: categories
        description: "Product category definitions"
        columns:
          - name: categoryid
            description: "Primary key. Unique identifier for each product category."
            data_type: string
          - name: categoryname
            description: "Name of the product category."
            data_type: string

      - name: countries
        description: "Country-level metadata"
        columns:
          - name: countryid
            description: "Primary key. Unique identifier for each country."
            data_type: string
          - name: countryname
            description: "Name of the country."
            data_type: string
          - name: countrycode
            description: "ISO 3166-1 alpha-2 country code."
            data_type: string

      - name: cities
        description: "City-level geographic data"
        columns:
          - name: cityid
            description: "Primary key. Unique identifier for each city."
            data_type: string
          - name: cityname
            description: "Name of the city."
            data_type: string
          - name: zipcode
            description: "Zipcode of the city."
            data_type: string
          - name: countryid
            description: "Foreign key to countries table."
            data_type: string

      - name: customers
        description: "Customer master data"
        columns:
          - name: customerid
            description: "Primary key. Unique identifier for each customer."
            data_type: string
          - name: firstname
            description: "First name of the customer."
            data_type: string
          - name: middleinitial
            description: "Middle initial of the customer."
            data_type: string
          - name: lastname
            description: "Last name of the customer."
            data_type: string
          - name: cityid
            description: "Foreign key to cities table."
            data_type: string
          - name: address
            description: "Residential address of the customer."
            data_type: string

      - name: employees
        description: "Employee/salesperson master data"
        columns:
          - name: employeeid
            description: "Primary key. Unique identifier for each employee."
            data_type: string
          - name: firstname
            description: "First name of the employee."
            data_type: string
          - name: middleinitial
            description: "Middle initial of the employee."
            data_type: string
          - name: lastname
            description: "Last name of the employee."
            data_type: string
          - name: birthdate
            description: "Date of birth of the employee."
            data_type: string
          - name: gender
            description: "Gender of the employee."
            data_type: string
          - name: cityid
            description: "Foreign key to cities table."
            data_type: string
          - name: hiredate
            description: "Date when the employee was hired."
            data_type: string

      - name: products
        description: "Product catalog"
        columns:
          - name: productid
            description: "Primary key. Unique identifier for each product."
            data_type: string
          - name: productname
            description: "Name of the product."
            data_type: string
          - name: price
            description: "Price per unit of the product."
            data_type: string
          - name: categoryid
            description: "Foreign key to categories table."
            data_type: string
          - name: class
            description: "Classification of the product."
            data_type: string
          - name: modifydate
            description: "Last modified date."
            data_type: string
          - name: resistant
            description: "Product resistance category."
            data_type: string
          - name: isallergic
            description: "Indicates whether the item is an allergen."
            data_type: string
          - name: vitalitydays
            description: "Product vitality/shelf-life classification."
            data_type: string

      - name: sales
        description: "Sales transactions"
        columns:
          - name: salesid
            description: "Primary key. Unique identifier for each sale."
            data_type: string
          - name: salespersonid
            description: "Foreign key to employees table."
            data_type: string
          - name: customerid
            description: "Foreign key to customers table."
            data_type: string
          - name: productid
            description: "Foreign key to products table."
            data_type: string
          - name: quantity
            description: "Number of units sold."
            data_type: string
          - name: discount
            description: "Discount applied to the sale."
            data_type: string
          - name: totalprice
            description: "Final sale price after discounts."
            data_type: string
          - name: salesdate
            description: "Date and time of the sale."
            data_type: string
          - name: transactionnumber
            description: "Unique identifier for the transaction."
            data_type: string
          - name: partition
            description: "Partition identifier for the data file."
